import Head from 'next/head';
import MainImage from '../public/MainImage.png';
import imgAbout from '../public/ImageAbout.png';
// import localFont from 'next/font/local'


export default function Home() {
	// const myFont = localFont({ src: './my-font.woff2' })

	return (
		<>
			<Head>
				<title>Bestari Journey</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com"/>
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
				<link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet"/>
			</Head>
			<div >
				<nav className="bg-white px-2 sm:px-6 py-6 dark:bg-gray-900 w-full top-0 left-0">
					<div className="container flex flex-wrap items-center justify-between mx-auto w-10/12">
						<a href="https://flowbite.com/" className="flex items-center">
							<svg className="h-6 mr-3 sm:h-9" id="logo-35" width="50" height="39" viewBox="0 0 50 39" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M16.4992 2H37.5808L22.0816 24.9729H1L16.4992 2Z" className="ccompli1" fill="#b34701" stopColor="#b34701"></path> <path d="M17.4224 27.102L11.4192 36H33.5008L49 13.0271H32.7024L23.2064 27.102H17.4224Z" className="ccustom" fill="#f76201" stopColor="#f76201"></path> </svg>
						</a>
						<div className="flex md:order-2">
							{/* <svg fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"  >
								<path stroke-linecap="round" stroke-linejoin="round" d="M2.25 6.75c0 8.284 6.716 15 15 15h2.25a2.25 2.25 0 002.25-2.25v-1.372c0-.516-.351-.966-.852-1.091l-4.423-1.106c-.44-.11-.902.055-1.173.417l-.97 1.293c-.282.376-.769.542-1.21.38a12.035 12.035 0 01-7.143-7.143c-.162-.441.004-.928.38-1.21l1.293-.97c.363-.271.527-.734.417-1.173L6.963 3.102a1.125 1.125 0 00-1.091-.852H4.5A2.25 2.25 0 002.25 4.5v2.25z"></path>
							</svg> */}
							{/* <span className="text-[#FA7436]" style={{ fontSize: '12px' }}>+62 82819282372</span> */}
							{/* <button type="button" className="text-white bg-[#FA7436] hover:bg-[#b05d37] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-black dark:hover:bg-[#3f4579] dark:focus:ring-[#3f4579]">Sign Up</button> */}
						</div>
						<div className="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
							<ul className="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
								<li>
									<a href="#"
										className="block py-2 pl-3 pr-4 text-white bg-black rounded md:bg-transparent md:text-[#FA7436] md:p-0 dark:text-white" aria-current="page"
										style={{ fontSize: '12px' }}>HOME</a>
								</li>
								<li>
									<a href="#"
										className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-[#FA7436] md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
										style={{ fontSize: '12px' }}>ABOUT US</a>
								</li>
								<li>
									<a href="#"
										className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-[#FA7436] md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
										style={{ fontSize: '12px' }}>MOUNTAINEERING</a>
								</li>
								<li>
									<a href="#"
										className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-[#FA7436] md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
										style={{ fontSize: '12px' }}>GALLERY</a>
								</li>
								<li>
									<a href="#"
										className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-[#FA7436] md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
										style={{ fontSize: '12px' }}>CONTACT</a>
								</li>
							</ul>
						</div>
					</div>
				</nav>
			</div>
			<div className='w-10/12 pt-14' style={{ margin: '0 auto' }}>
				<div className="grid grid-cols-2 gap-4">
					<div clasName="" style={{ padding: '40px' }}>
						<h4 className="" style={{ fontWeight: 'bold', fontSize: '76px' }}>It's a Big World Out There, <span className="text-[#FA7436]">Go Explore</span></h4>
					</div>
					<div className="flex items-center"  style={{ padding: '40px' }}>
						<div className=''>
							<h5 style={{ fontSize: '24px' }} className="text-[#444444]">Time tracking software used by millions. A simple time tracker and timesheet app that lets you track work hours across projects......</h5>
							<button type="button" className="mt-12 text-white bg-[#FA7436] hover:bg-[#b05d37] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-black dark:hover:bg-[#3f4579] dark:focus:ring-[#3f4579]">
								Discover Now
							</button>
						</div>
					</div>
				</div>
				<div>
					{/*
					<div className="static">
						<a href="#" className="absolute block w-10/12 p-6 ">
							<h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
							<p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
						</a>
					</div> */}
					<div className="relative">
						<img className="h-auto w-full mt-8"
							src="https://images.unsplash.com/photo-1551632811-561732d1e306?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="" />

						<div className="grid justify-items-center">
							<div className=" absolute h-32 -bottom-12 w-10/12 bg-white border border-gray-200 rounded-lg shadow">
								<div className="grid grid-cols-5 gap-4 p-6">
									<div className="...">
										<div>
											<label htmlFor="email-address-icon" className="md:ml-4 block mb-2 text-sm font-medium text-gray-900 dark:text-white" >From</label>
											<div className="relative">
												<div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
													<svg aria-hidden="true" className="w-5 h-5 text-[#FA7436] dark:text-[#E4D4CB]" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"  >
														<path strokeLinecap="round" strokeLinejoin="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0z" />
														<path strokeLinecap="round" strokeLinejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0z" />
													</svg>
												{/* <svg aria-hidden="true" className="w-5 h-5 text-gray-500 dark:text-[#E4D4CB]" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" /><path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" /></svg> */}
												</div>
												<input type="text" id="email-address-icon"
													style={{ borderRadius: '20px' }}
													className="bg-white border border-[#E4D4CB] text-gray-500 text-sm focus:ring-[#FA7436] focus:border-[#FA7436] block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-[#E4D4CB] dark:focus:border-[#E4D4CB]"
													placeholder="Cawang, Jakarta" />
											</div>
										</div>
									</div>
									<div className="...">
										<div>
											<label htmlFor="email-address-icon" className="md:ml-4 block mb-2 text-sm font-medium text-gray-900 dark:text-white" >To</label>
											<div className="relative">
												<div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
													<svg aria-hidden="true" className="w-5 h-5 text-[#FA7436] dark:text-[#E4D4CB]" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"  >
														<path strokeLinecap="round" strokeLinejoin="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0z" />
														<path strokeLinecap="round" strokeLinejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0z" />
													</svg>
												{/* <svg aria-hidden="true" className="w-5 h-5 text-gray-500 dark:text-[#E4D4CB]" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" /><path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" /></svg> */}
												</div>
												<input type="text" id="email-address-icon"
													style={{ borderRadius: '20px' }}
													className="bg-white border border-[#E4D4CB] text-gray-500 text-sm focus:ring-[#FA7436] focus:border-[#FA7436] block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-[#E4D4CB] dark:focus:border-[#E4D4CB]"
													placeholder="Rinjani, Sembalun" />
											</div>
										</div>
									</div>
									<div className="...">
										<div>
											<label htmlFor="email-address-icon" className="md:ml-4 block mb-2 text-sm font-medium text-gray-900 dark:text-white" >Dates</label>
											<div className="relative">
												<div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
													<svg aria-hidden="true" className="w-5 h-5 text-[#FA7436] dark:text-[#E4D4CB]" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"  >
														<path strokeLinecap="round" strokeLinejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5m-9-6h.008v.008H12v-.008zM12 15h.008v.008H12V15zm0 2.25h.008v.008H12v-.008zM9.75 15h.008v.008H9.75V15zm0 2.25h.008v.008H9.75v-.008zM7.5 15h.008v.008H7.5V15zm0 2.25h.008v.008H7.5v-.008zm6.75-4.5h.008v.008h-.008v-.008zm0 2.25h.008v.008h-.008V15zm0 2.25h.008v.008h-.008v-.008zm2.25-4.5h.008v.008H16.5v-.008zm0 2.25h.008v.008H16.5V15z" />
													</svg>
												{/* <svg aria-hidden="true" className="w-5 h-5 text-gray-500 dark:text-[#E4D4CB]" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" /><path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" /></svg> */}
												</div>
												<input type="text" id="email-address-icon"
													style={{ borderRadius: '20px' }}
													className="bg-white border border-[#E4D4CB] text-gray-500 text-sm focus:ring-[#FA7436] focus:border-[#FA7436] block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-[#E4D4CB] dark:focus:border-[#E4D4CB]"
													placeholder="Select Schedule" />
											</div>
										</div>
									</div>
									<div className="...">
										<div>
											<label htmlFor="email-address-icon" className="md:ml-4 block mb-2 text-sm font-medium text-gray-900 dark:text-white" >Guest</label>
											<div className="relative">
												<div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
													<svg aria-hidden="true" className="w-5 h-5 text-[#FA7436] dark:text-[#E4D4CB]" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"  >
														<path strokeLinecap="round" strokeLinejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />
													</svg>
												{/* <svg aria-hidden="true" className="w-5 h-5 text-gray-500 dark:text-[#E4D4CB]" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" /><path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" /></svg> */}
												</div>
												<input type="text" id="email-address-icon"
													style={{ borderRadius: '20px' }}
													className="bg-white border border-[#E4D4CB] text-gray-500 text-sm focus:ring-[#FA7436] focus:border-[#FA7436] block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-[#E4D4CB] dark:focus:border-[#E4D4CB]"
													placeholder="Number of Guest" />
											</div>
										</div>
									</div>
									<div className="">
										<div>
											<label htmlFor="email-address-icon" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"> &nbsp;</label>
											<div className="relative flex items-center">
												<button type="button"
													style={{ borderRadius: '20px' }}
													className="flex text-white bg-[#FA7436] hover:bg-[#b05d37] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-black dark:hover:bg-[#3f4579] dark:focus:ring-[#3f4579]">
													<svg aria-hidden="true" className="w-5 h-5 text-[#fff] dark:text-[#E4D4CB]"  fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
														<path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
													</svg>
													&nbsp;
													<span className="text-white-900">Check Quota</span>
												</button>
											</div>
										</div>
									</div>
								</div>

							</div>
						</div>
					</div>

					<div className="grid grid-cols-2 gap-4 md:mt-32 bg-[#F7F8FC] h-4/5 pt-8" >
						<div className="">
							<img className="h-auto"
								src='/ImageAbout.png' alt="" />

						</div>
						<div className="...">
							<h4 className="text-[#FA7436]">ABOUT US</h4>
							<h4 className="mr-24 mt-8" style={{ fontSize: '54px', fontFamily: 'Lato' }}>The Best And Most trusted <span className='text-[#FA7436]'>service</span></h4>
							<h4 className="mr-24 mt-8">We are the largest holiday service provider in the world with partners and places spread all over the world by prioriti-zing service and customer satisfaction.</h4>
							<button type="button" className="mt-12 text-white bg-[#FA7436] hover:bg-[#b05d37] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-black dark:hover:bg-[#3f4579] dark:focus:ring-[#3f4579]">
								Learn More
							</button>
							<div className="grid grid-flow-col auto-cols-max mt-20">
								<div className="pr-12">
									<h2 style={{ fontSize: '24px' }} className="text-[#FA7436]">200+</h2>
									<h4>Customer <br/>& Partners</h4>
								</div>
								<div className="pr-12">
									<h2 style={{ fontSize: '24px' }} className="text-[#FA7436]">200+</h2>
									<h4>Customer <br/>& Partners</h4>
								</div>
								<div className="pr-12">
									<h2 style={{ fontSize: '24px' }} className="text-[#FA7436]">200+</h2>
									<h4>Customer <br/>& Partners</h4>
								</div>
							</div>
						</div>
  					</div>

					<div className=' md:mt-32 '>
						<h2 style={{ textAlign: 'center', fontSize: '48px', fontFamily: 'Lato' }}>
							The <span className="text-[#FA7436]">best place</span> for vacation
						</h2>
						<div className="grid justify-items-center my-12">
							<ul className="flex text-gray-500 list-inside dark:text-gray-400">
								<li className="px-8">
									Special Deals
								</li>
								<li className="px-8">
									Popular
								</li>
								<li className="px-8">
									Recomendation
								</li>
								<li className="px-8">
									Best Price
								</li>
							</ul>
						</div>

						<div class="grid grid-cols-4 gap-4 justify-items-center">
							<div>
								<a href="#" className="block max-w-sm bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
									<img className="w-full h-64 rounded-lg" style={{ objectFit: 'cover' }} src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image.jpg" alt="" />

									<div class="grid grid-cols-2 gap-4 p-4">
										<div className="flex">
											{/* <svg aria-hidden="true" className="w-5 h-5 text-[#FA7436] dark:text-[#E4D4CB]" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"  >
												<path strokeLinecap="round" strokeLinejoin="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0z" />
												<path strokeLinecap="round" strokeLinejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0z" />
											</svg> */}
											<svg className="w-5 h-5 text-[#FA7436] dark:text-[#FA7436]"  fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
												<path clipRule="evenodd" fillRule="evenodd" d="M11.54 22.351l.07.04.028.016a.76.76 0 00.723 0l.028-.015.071-.041a16.975 16.975 0 001.144-.742 19.58 19.58 0 002.683-2.282c1.944-1.99 3.963-4.98 3.963-8.827a8.25 8.25 0 00-16.5 0c0 3.846 2.02 6.837 3.963 8.827a19.58 19.58 0 002.682 2.282 16.975 16.975 0 001.145.742zM12 13.5a3 3 0 100-6 3 3 0 000 6z" />
											</svg>
											&nbsp;
											<span className="text-[#FA7436]">Mt. Rinjani</span>
										</div>
										<div className="flex justify-items-end" style={{ textAlign: 'end' }}>
											<svg className="w-5 h-5 text-[#FFCA00] dark:text-[#FFCA00]" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
												<path clipRule="evenodd" fillRule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" />
											</svg>
											&nbsp;
											<span>4.7</span>
										</div>
									</div>

									<h5 className="text-2xl pl-6 pb-4 font-bold tracking-tight text-gray-900 dark:text-white">Hurawalhi Island</h5>
									<p style={{ fontSize: '12px'}} className="pl-6 ob-4 text-[#999999] dark:text-[#999999]">7 Days Tour on 2 person</p>
									<h5 className="text-2xl pl-6 pb-4 font-bold tracking-tight text-gray-900 dark:text-white">620$</h5>
								</a>
							</div>
							<div>
								<a href="#" className="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
									<h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
									<p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
								</a>
							</div>
							<div>
								<a href="#" className="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
									<h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
									<p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
								</a>
							</div>
							<div>
								<a href="#" className="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
									<h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
									<p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
								</a>
							</div>
							<div>
								<a href="#" className="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
									<h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
									<p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
								</a>
							</div>
							<div>
								<a href="#" className="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
									<h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
									<p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
								</a>
							</div>
						</div>
						{/* <div className="grid grid-cols-4 gap-4bg-[#fff] h-80 mt-12 w-8/12 justify-items-center" >
							<div className="...">
								Special Deals
							</div>
							<div className="...">
								Popular
							</div>
							<div className="...">
								Recomendation
							</div>
							<div className="...">
								Best Price
							</div>
						</div> */}
					</div>

				</div>
			</div>

			{/* <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
				<div className="grid gap-4">
					<div>
					<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image.jpg" alt="" />
					</div>
					<div>
					<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-1.jpg" alt="" />
					</div>
					<div>
					<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-2.jpg" alt="" />
					</div>
				</div>
				<div className="grid gap-4">
					<div>
					<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-3.jpg" alt="" />
					</div>
					<div>
					<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-4.jpg" alt="" />
					</div>
					<div>
					<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-5.jpg" alt="" />
					</div>
				</div>
				<div className="grid gap-4">
					<div>
					<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-6.jpg" alt="" />
					</div>
					<div>
					<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-7.jpg" alt="" />
					</div>
					<div>
					<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-8.jpg" alt="" />
					</div>
				</div>
				<div className="grid gap-4">
					<div>
					<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-9.jpg" alt="" />
					</div>
					<div>
					<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-10.jpg" alt="" />
					</div>
					<div>
					<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-11.jpg" alt="" />
					</div>
				</div>
			</div> */}

			
				
		</>
	)
}
