import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    	<Head>
			<title>Bestari Journey</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<div >
			<nav className="bg-white px-2 sm:px-4 py-2.5 dark:bg-gray-900 w-full top-0 left-0">
			<div className="container flex flex-wrap items-center justify-between mx-auto">
				<a href="https://flowbite.com/" className="flex items-center">
					<svg className="h-6 mr-3 sm:h-9" id="logo-35" width="50" height="39" viewBox="0 0 50 39" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M16.4992 2H37.5808L22.0816 24.9729H1L16.4992 2Z" className="ccompli1" fill="#b34701" stopColor="#b34701"></path> <path d="M17.4224 27.102L11.4192 36H33.5008L49 13.0271H32.7024L23.2064 27.102H17.4224Z" className="ccustom" fill="#f76201" stopColor="#f76201"></path> </svg>
				</a>
				<div className="flex md:order-2">
					<button type="button" className="text-white bg-black hover:bg-[#f76201] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-black dark:hover:bg-[#f76201] dark:focus:ring-[#f76201]">Sign Up</button>
				</div>
				<div className="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
					<ul className="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
						<li>
							<a href="#" className="block py-2 pl-3 pr-4 text-white bg-black rounded md:bg-transparent md:text-[#f76201] md:p-0 dark:text-white" aria-current="page">Home</a>
						</li>
						<li>
							<a href="#" className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-[#f76201] md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
						</li>
						<li>
							<a href="#" className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-[#f76201] md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Destination</a>
						</li>
						<li>
							<a href="#" className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-[#f76201] md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Tour</a>
						</li>
						<li>
							<a href="#" className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-[#f76201]0 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Blog</a>
						</li>
					</ul>
				</div>
			</div>
			</nav>
		</div>
		<div className='w-9/12' style={{ margin: '0 auto' }}>
			<div className="grid grid-cols-3 gap-4 md:mt-16">
				<div className="col-span-2">
					<img className="max-w-full h-4/5 md:w-full rounded-lg" src="https://images.unsplash.com/photo-1426604966848-d7adac402bff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="" />
				</div>
				<div className="...">
					<div className="grid grid-rows-4 grid-flow-col gap-4 m-6">
						<div className="grid grid-flow-col w-full h-20">
							<a href="#" className="block max-w-sm p-2 bg-white">
								<div className="grid grid-cols-3 gap-4 justify-items-end">
									<div className=' '>
										<img className="w-14 h-14 rounded-full" src="https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="Rounded avatar" />
									</div>
									<div className="col-span-2">
										<h6 className="mb-2 text-sm font-bold tracking-tight text-gray-900 dark:text-white">Windsurfing</h6>
										<p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise.</p> 
									</div>
								</div>
							</a>
						</div>

						<div className="grid grid-flow-col w-full h-20">
							<a href="#" className="block max-w-sm p-2 bg-white">
								<div className="grid grid-cols-3 gap-4 justify-items-end">
									<div className=' '>
										<img className="w-14 h-14 rounded-full" src="https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="Rounded avatar" />
									</div>
									<div className="col-span-2">
										<h6 className="mb-2 text-sm font-bold tracking-tight text-gray-900 dark:text-white">Windsurfing</h6>
										<p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise.</p> 
									</div>
								</div>
							</a>
						</div>

						<div className="grid grid-flow-col w-full h-20">
							<a href="#" className="block max-w-sm p-2 bg-white">
								<div className="grid grid-cols-3 gap-4 justify-items-end">
									<div className=' '>
										<img className="w-14 h-14 rounded-full" src="https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="Rounded avatar" />
									</div>
									<div className="col-span-2">
										<h6 className="mb-2 text-sm font-bold tracking-tight text-gray-900 dark:text-white">Windsurfing</h6>
										<p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise.</p> 
									</div>
								</div>
							</a>
						</div>

						<div className="grid grid-flow-col w-full h-20">
							<a href="#" className="block max-w-sm p-2 bg-white">
								<div className="grid grid-cols-3 gap-4 justify-items-end">
									<div className=' '>
										<img className="w-14 h-14 rounded-full" src="https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="Rounded avatar" />
									</div>
									<div className="col-span-2">
										<h6 className="mb-2 text-sm font-bold tracking-tight text-gray-900 dark:text-white">Windsurfing</h6>
										<p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise.</p> 
									</div>
								</div>
							</a>
						</div>
					</div>
				</div>
			</div>
			<div className="block h-28 w-ful bg-white border border-gray-200 rounded-lg shadow ">
				<div className="grid grid-cols-3 gap-4">
					<div className="">
						
					</div>
					<div className="col-span-2 ...">07</div>
				</div>
			</div>
			{/* <a href="#" className="block max-w-sm p-6 w-full bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
				<h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
				<p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
			</a> */}

		</div>

		{/* <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
			<div className="grid gap-4">
				<div>
				<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image.jpg" alt="" />
				</div>
				<div>
				<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-1.jpg" alt="" />
				</div>
				<div>
				<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-2.jpg" alt="" />
				</div>
			</div>
			<div className="grid gap-4">
				<div>
				<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-3.jpg" alt="" />
				</div>
				<div>
				<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-4.jpg" alt="" />
				</div>
				<div>
				<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-5.jpg" alt="" />
				</div>
			</div>
			<div className="grid gap-4">
				<div>
				<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-6.jpg" alt="" />
				</div>
				<div>
				<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-7.jpg" alt="" />
				</div>
				<div>
				<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-8.jpg" alt="" />
				</div>
			</div>
			<div className="grid gap-4">
				<div>
				<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-9.jpg" alt="" />
				</div>
				<div>
				<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-10.jpg" alt="" />
				</div>
				<div>
				<img className="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-11.jpg" alt="" />
				</div>
			</div>
		</div> */}

		
			
    </>
  )
}
